# Generated by Django 2.2.6 on 2019-10-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phoneNumber', models.IntegerField(default=0)),
                ('Balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ATMCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATMCardNumber', models.IntegerField(default=0)),
                ('PIN', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('DOI', models.IntegerField(default=0)),
                ('ExpirationDate', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=200)),
                ('AccountNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atm.Account')),
            ],
        ),
        migrations.DeleteModel(
            name='choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
