# Generated by Django 2.2.6 on 2019-10-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_auto_20191018_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='AccountNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='phoneNumber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='ATMCardNumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='DOI',
            field=models.DateField(verbose_name='Date Issued: '),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='ExpirationDate',
            field=models.DateField(),
        ),
    ]
